apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-configmap: 'vault-sidecar-node'
    spec:
      containers:
        - name: node-app
          image: devendranathashok/nodejs:2.0.2
      serviceAccountName: vault-auth
