apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-sidecar-node
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
          "token_path" = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
        "contents" = "secret {\n  no_prefix = true\n   path = \"kv/dev/apps/service01\"\n } \nvault {\n   {{- with secret \"auth/token/lookup-self\" -}}\n token = \"{{ .Data.id}}\"\n {{- end}}\n  address = \"http://vault.vault.svc:8200\"\n  renew_token = false\n }\n"
        "destination" = "/vault/secrets/envconsul-config.hcl"
      }

    "vault" = {
      "address" = "http://vault.vault.svc:8200"
    }
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "webapp"
          "token_path" = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
        "contents" = "secret {\n  no_prefix = true\n  path = \"kv/dev/apps/service01\"\n } \nvault {\n   {{- with secret \"auth/token/lookup-self\" -}}\n token = \"{{ .Data.id}}\"\n {{- end}}\n  address = \"http://vault.vault.svc:8200\"\n  renew_token = false\n }\n"
        "destination" = "/vault/secrets/envconsul-config.hcl"
      }


    "vault" = {
      "address" = "http://vault.vault.svc:8200"
    }

